# Generated by Django 4.2.5 on 2023-09-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_to_home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='image',
            field=models.ImageField(upload_to='MEDIA/'),
        ),
    ]
